POPULAR_TARGET_BRANDS = [
    "paypal",
    "google",
    "microsoft",
    "apple",
    "amazon",
    "netflix",
    "facebook",
    "instagram",
    "chase",
    "wellsfargo",
    "bankofamerica",
    "citi",
    "binance",
    "coinbase",
    "dhl",
    "fedex",
    "usps",
]

SUSPICIOUS_URL_KEYWORDS = [
    "login",
    "verify",
    "verification",
    "secure",
    "account",
    "password",
    "update",
    "confirm",
    "wallet",
    "banking",
    "signin",
    "auth",
    "support",
    "service",
    "portal",
    "bill",
    "invoice",
    "recover",
    "session",
]

URGENCY_KEYWORDS = [
    "urgent",
    "immediately",
    "suspended",
    "terminate",
    "24 hours",
    "within 1 hour",
    "action required",
    "compromised",
    "unauthorized",
    "final warning",
    "account closed",
    "locked",
]

CREDENTIAL_HARVEST_KEYWORDS = [
    "enter your password",
    "confirm your otp",
    "bank account details",
    "social security",
    "card number",
    "cvv",
    "seed phrase",
    "secret key",
    "verify identity",
    "submit credentials",
]

SUSPICIOUS_EXTENSIONS = {
    ".exe",
    ".scr",
    ".bat",
    ".cmd",
    ".vbs",
    ".js",
    ".wsf",
    ".ps1",
    ".jar",
    ".msi",
    ".dll",
    ".hta",
    ".iso",
    ".img",
    ".docm",
    ".xlsm",
}

DOUBLE_EXTENSION_PATTERNS = [
    ".pdf.exe",
    ".doc.exe",
    ".docx.exe",
    ".jpg.exe",
    ".png.exe",
    ".pdf.vbs",
    ".xlsx.vbs",
    ".zip.exe",
]

URL_SHORTENERS = [
    "bit.ly",
    "tinyurl.com",
    "t.co",
    "is.gd",
    "cutt.ly",
    "goo.gl",
    "ow.ly",
]
